//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use crate::apps::user::constants::{ClassType, GenderType};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uid: String,
    pub r#type: ClassType,
    pub nickname: String,
    pub password: String,
    pub name: Option<String>,
    pub gender: Option<GenderType>,
    pub telephone: Option<String>,
    pub email: Option<String>,
    pub address: Option<String>,
    pub last_login_dt: Option<DateTimeLocal>,
    pub create_ts: DateTimeLocal,
    pub update_ts: DateTimeLocal,
    pub delete_ts: Option<DateTimeLocal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
