//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::edu_account::Entity as EduAccount;
pub use super::edu_student::Entity as EduStudent;
pub use super::edu_teacher::Entity as EduTeacher;
