//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.36

use crate::soft_delete;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[soft_delete]
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique, comment = "账户唯一标识")]
    pub uid: String,
    #[sea_orm(comment = "账户类型;1:用户;2:内部人员")]
    pub r#type: i16,
    #[sea_orm(comment = "昵称")]
    pub nickname: String,
    #[sea_orm(comment = "密码")]
    pub password: String,
    #[sea_orm(comment = "用户名")]
    pub name: Option<String>,
    #[sea_orm(comment = "性别;1:男;2:女", default_value = "0")]
    pub gender: i16,
    #[sea_orm(comment = "手机号码")]
    pub telephone: Option<String>,
    #[sea_orm(comment = "邮件地址")]
    pub email: Option<String>,
    #[sea_orm(comment = "居住地址")]
    pub address: Option<String>,
    #[sea_orm(comment = "最后登录时间")]
    pub last_login_dt: Option<DateTime>,
    #[sea_orm(default_expr = "Expr::current_timestamp()", comment = "创建时间")]
    pub create_ts: DateTime,
    #[sea_orm(default_expr = "Expr::current_timestamp()", comment = "更新时间")]
    pub update_ts: DateTime,
    #[sea_orm(comment = "删除时间")]
    pub delete_ts: Option<DateTime>,
}
