//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uid: String,
    pub r#type: u8,
    pub nickname: String,
    pub password: String,
    pub name: Option<String>,
    pub gender: u8,
    pub telephone: Option<String>,
    pub email: Option<String>,
    pub address: Option<String>,
    pub last_login_dt: Option<DateTime>,
    pub create_ts: DateTime,
    pub update_ts: DateTime,
    pub delete_ts: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
