//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "chat_message_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub session_id: String,
    #[sea_orm(unique)]
    pub message_id: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub input: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub output: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
