//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12
// 在这里去除了 Entity, 因为觉得从文件导出很奇怪
pub use super::account as Account;
pub use super::chat_message_history as ChatMessageHistory;
pub use super::chat_session as ChatSession;
